version: '3'

services:
  build:
    image: ${APP}
    command: cargo build -r
    build:
      context: .

  test:
    image: ${APP}
    command: cargo llvm-cov

  lint:
    image: ${APP}
    volumes:
      - ./:/rwc
    environment:
      - __CARGO_FIX_YOLO=1
    command: cargo clippy --fix --allow-no-vcs