services:
  build:
    image: ${APP}
    command: cargo build -r
    build:
      context: .

  coverage:
    image: ${APP}
    command: cargo llvm-cov

  lint:
    image: ${APP}
    environment:
      - __CARGO_FIX_YOLO=1
    command: cargo clippy --fix