name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@nightly
    - name: Build
      run: cargo build --verbose

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use nightly toolchain
      uses: dtolnay/rust-toolchain@nightly

    - name: Use llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov

    - name: Generate coverage
      run: cargo llvm-cov --lcov --output-path ./coverage.lcov

    - name: Upload coverage to coveralls
      uses: coverallsapp/github-action@v2

